### ISSUE TITLE
inputset generator to take an organization name and create an inputset with all the projects by that org

### ISSUE THREAD

**Issue by minusworld** [returntocorp/inputset-generator#13]

**Comment by ievans** [comment]
@minusworld I called @bafulton and asked him about this today. It's not currently implemented, and will take more than a few lines of code, but is not super hard.

**Comment by ievans** [comment]
cc @mschwager who I know talked with @DrewDennison about this

**Comment by bafulton** [comment]
It turned out to be fairly easy (and super fun!). Here's the PR: https://github.com/returntocorp/inputset-generator/pull/14

**Comment by ievans** [comment]
```
r2c-isg> load github org netflix
         Loaded 177 projects containing 0 total versions.
r2c-isg> export netflix.json
         Exception: The dataset must have a name and version. Set them using the 'set-meta -n NAME -v VERSION' command.
r2c-isg> set-meta -n netflix-2020-01-23 -v 0.0.1
         AttributeError: 'Dataset' object has no attribute 'configure'
```
@bafulton @minusworld seeing this exception when trying to do my use case ^

**Comment by bafulton** [comment]
@ievans, @minusworld, it's a bug introduced by PR #14. Fixed by PR #15.
